// packages/react-sdk/src/cms/BrContainerBox.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from 'react';
import { BrProps } from '../component';

export function BrContainerBox({ page, children }: React.PropsWithChildren<BrProps>): React.ReactElement {
  return (
    <div className={page?.isPreview() ? 'hst-container' : undefined}>
      {React.Children.map(children, (child) => (
        <div className={page?.isPreview() ? 'hst-container-item' : undefined}>{child}</div>
      ))}
    </div>
  );
}

// packages/vue3-sdk/src/BrContainerBox.vue
<!--
  Copyright 2023 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<template>
  <render />
</template>

<script setup lang="ts">
import type { Page } from '@bloomreach/spa-sdk';
import { computed, h, useSlots } from 'vue';

const props = defineProps<{ page?: Page }>();
const slots = useSlots();
const isPreview = computed(() => props.page?.isPreview());

const render = () => h(
  'div',
  { class: { 'hst-container': isPreview } },
  slots.default?.().map((node) => h(
    'div',
    { class: { 'hst-container-item': isPreview } },
    [node],
  )),
);
</script>
