// examples/next/components/Content.tsx
/*
 * Copyright 2019-2023 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {BrManageContentButton, BrProps} from '@bloomreach/react-sdk';
import {Document, ImageSet} from '@bloomreach/spa-sdk';
import React from 'react';
import {sanitize} from "../utils/sanitize";

export function Content(props: BrProps): JSX.Element | null {
  const documentRef = props.component?.getModels<DocumentModels>().document;
  const document = documentRef && props.page?.getContent<Document>(documentRef);

  if (!document) {
    return null;
  }

  const {
    author,
    content,
    publicationDate,
    date = publicationDate,
    image: imageRef,
    title,
  } = document.getData<DocumentData>();
  const image = imageRef && props.page?.getContent<ImageSet>(imageRef);

  return (
    <div className={props.page?.isPreview() ? 'has-edit-button' : ''}>
      <BrManageContentButton content={document}/>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      {image && <img className="img-fluid mb-3" src={image.getOriginal()?.getUrl()} alt={title}/>}
      {title && <h1>{title}</h1>}
      {author && <p className="mb-3 text-muted">{author}</p>}
      {date && <p className="mb-3 small text-muted">{new Date(date).toDateString()}</p>}
      {content && (
        <div dangerouslySetInnerHTML={{__html: props.page!.rewriteLinks(sanitize(content.value))}}/>
      )}
    </div>
  );
}

// examples/angular/src/app/components/content/content.component.ts
/*
 * Copyright 2024 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, Input, OnInit } from '@angular/core';
import { Component as BrComponent, Document, ImageSet, Page } from '@bloomreach/spa-sdk';
import { CommonModule } from '@angular/common';
import { BrSdkModule } from '@bloomreach/ng-sdk';
import { sanitize } from '../../utils/sanitize';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'br-content',
  standalone: true,
  imports: [
    CommonModule,
    BrSdkModule,
  ],
  templateUrl: './content.component.html',
})
export class ContentComponent implements OnInit {
  @Input() component!: BrComponent;

  @Input() page!: Page;

  safeHTML?: string | null;

  async ngOnInit(): Promise<void> {
    const content = this.document?.getData<DocumentData>().content;
    const sanitized = sanitize(content!.value);
    this.safeHTML = this.page.rewriteLinks(sanitized);
  }

  get document(): Document | undefined {
    const { document } = this.component.getModels<DocumentModels>();

    return document && this.page.getContent<Document>(document);
  }

  get data(): DocumentData | undefined {
    return this.document?.getData<DocumentData>();
  }

  get date(): number | undefined {
    return this.data?.date ?? this.data?.publicationDate;
  }

  get image(): ImageSet | undefined {
    return this.data?.image && this.page.getContent<ImageSet>(this.data.image);
  }
}

<!--
  Copyright 2024 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
@if (document) {
<div [ngClass]="{ 'has-edit-button': page.isPreview() }">
  <ng-container [brManageContentButton]="document"></ng-container>
  @if (image) {
  <img class="img-fluid" [src]="image.getOriginal()?.getUrl()" [alt]="data?.title || ''" />
  }
  @if (data?.title) {
  <h1>{{ data!.title }}</h1>
  }
  @if (data?.author) {
  <p class="mb-3 text-muted">{{ data!.author }}</p>
  }
  @if (date) {
  <p class="mb-3 small text-muted">{{ date | date }}</p>
  }
  @if (data?.content) {
  <div [innerHTML]="safeHTML"></div>
  }
</div>
}
