// examples/react/src/components/NewsList.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { JSX } from 'react';
import { Link } from 'react-router-dom';
import { Document, Page } from '@bloomreach/spa-sdk';
import { BrManageContentButton, BrProps } from '@bloomreach/react-sdk';

interface NewsListItemProps {
  item: Document;
  page: Page;
}

export function NewsListItem({ item, page }: NewsListItemProps): JSX.Element {
  const { author, date, introduction, title } = item.getData<DocumentData>();

  return (
    <div className="card mb-3">
      <BrManageContentButton content={item} page={page} />
      <div className="card-body">
        {title && (
          <h2 className="card-title">
            <Link to={item.getUrl() || ''}>{title}</Link>
          </h2>
        )}
        {author && <div className="card-subtitle mb-3 text-muted">{author}</div>}
        {date && <div className="card-subtitle mb-3 small text-muted">{new Date(date).toDateString()}</div>}
        {introduction && <p className="card-text">{introduction}</p>}
      </div>
    </div>
  );
}

type NewsListPaginationProps = Pick<
  Pageable,
  'showPagination' | 'previous' | 'previousPage' | 'pageNumbersArray' | 'currentPage' | 'next' | 'nextPage'
> & {
  page: Page;
};

export function NewsListPagination({
  showPagination,
  previous,
  previousPage,
  pageNumbersArray,
  currentPage,
  next,
  nextPage,
  page,
}: NewsListPaginationProps): JSX.Element | null {
  if (!page || !showPagination) {
    return null;
  }

  return (
    <nav aria-label="News List Pagination">
      <ul className="pagination">
        <li className={`page-item ${previous ? '' : 'disabled'}`}>
          <Link to={previous ? page.getUrl(`?page=${previousPage}`) : '#'} className="page-link" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span className="sr-only">Previous</span>
          </Link>
        </li>
        {pageNumbersArray.map((pageNumber, key) => (
          // eslint-disable-next-line react/no-array-index-key
          <li key={key} className={`page-item ${pageNumber === currentPage ? 'active' : ''}`}>
            <Link to={page.getUrl(`?page=${pageNumber}`)} className="page-link">
              {pageNumber}
            </Link>
          </li>
        ))}
        <li className={`page-item ${next ? '' : 'disabled'}`}>
          <Link to={next ? page.getUrl(`?page=${nextPage}`) : '#'} className="page-link" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span className="sr-only">Next</span>
          </Link>
        </li>
      </ul>
    </nav>
  );
}

export function NewsList({ component, page }: BrProps): JSX.Element | null {
  const pageable = component?.getModels<PageableModels>().pageable;

  if (!pageable) {
    return null;
  }

  return (
    <div>
      {pageable.items.map((reference, key) => (
        // eslint-disable-next-line react/no-array-index-key
        <NewsListItem key={key} item={page.getContent<Document>(reference) as Document} page={page} />
      ))}
      {page.isPreview() && (
        <div className="has-edit-button float-right">
          <BrManageContentButton
            documentTemplateQuery="new-news-document"
            folderTemplateQuery="new-news-folder"
            root="news"
            page={page}
          />
        </div>
      )}
      <NewsListPagination
        showPagination={pageable.showPagination}
        previousPage={pageable.previousPage}
        pageNumbersArray={pageable.pageNumbersArray}
        currentPage={pageable.currentPage}
        nextPage={pageable.nextPage}
        next={pageable.next}
        previous={pageable.previous}
        page={page}
      />
    </div>
  );
}

// examples/angular/src/app/components/news-list/news-list.component.ts
/*
 * Copyright 2024 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';
import { BrSdkModule } from '@bloomreach/ng-sdk';
import { Component as BrComponent, Page } from '@bloomreach/spa-sdk';
import { NewsItemComponent } from '../news-item/news-item.component';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'br-news-list',
  standalone: true,
  imports: [
    CommonModule,
    BrSdkModule,
    RouterModule,
    NewsItemComponent,
  ],
  templateUrl: './news-list.component.html',
})
export class NewsListComponent {
  @Input() component!: BrComponent;

  @Input() page!: Page;

  get pagination(): Pageable {
    return this.component.getModels<PageableModels>().pageable;
  }
}

<!--
  Copyright 2024 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

@if (pagination) {
@for (reference of pagination.items; track $index) {
<br-news-item [item]="page.getContent(reference)!"></br-news-item>
}

@if (page.isPreview()) {
<div class="has-edit-button float-right">
  <ng-container [brManageContentButton] documentTemplateQuery="new-news-document" folderTemplateQuery="new-news-folder"
    root="news">
  </ng-container>
</div>
}

@if (pagination.showPagination) {
<nav aria-label="News List Pagination">
  <ul class="pagination">
    <li class="page-item" [ngClass]="{ disabled: !pagination.previous }">
      <a class="page-link" aria-label="Previous" routerLink="./" [queryParams]="{ page: pagination.previousPage }"
        queryParamsHandling="merge">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    @for (page of pagination.pageNumbersArray; track $index) {
      <li class="page-item"
        [ngClass]="{ active: page === pagination.currentPage }">
        <a class="page-link" routerLink="./" [queryParams]="{ page: page }" queryParamsHandling="merge">
          {{ page }}
        </a>
      </li>
    }

    <li class="page-item" [ngClass]="{ disabled: !pagination.next }">
      <a class="page-link" aria-label="Next" routerLink="./" [queryParams]="{ page: pagination.nextPage }"
        queryParamsHandling="merge">
        <span class="sr-only">Next</span>
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
}
}
