// examples/vue3/src/App.vue
<!--
  Copyright 2023 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<template>
  <br-page :configuration="configuration" :mapping="mapping">
    <template v-slot="{ page }">
      <template v-if="page">
        <header>
          <nav class="navbar navbar-expand-sm navbar-dark sticky-top bg-dark" role="navigation">
            <div class="container">
              <router-link :to="page.getUrl('/')" class="navbar-brand">
                {{ page.getTitle() || 'brXM + Vue.js = ♥' }}
              </router-link>
              <div class="collapse navbar-collapse">
                <br-component component="menu"/>
              </div>
            </div>
          </nav>
        </header>
        <section class="container flex-fill pt-3">
          <br-component component="main"/>
        </section>
        <footer class="bg-dark text-light py-3">
          <div class="container clearfix">
            <div class="float-left pr-3">&copy; Bloomreach</div>
            <div class="overflow-hidden">
              <br-component component="bottom"/>
            </div>
          </div>
        </footer>
        <br-cookie-consent :isPreview="page.isPreview()" :path="configuration.path"></br-cookie-consent>
      </template>
    </template>
  </br-page>
</template>

<script setup lang="ts">
import BrBanner from '@/components/BrBanner.vue';
import BrContent from '@/components/BrContent.vue';
import BrCookieConsent from '@/components/BrCookieConsent.vue';
import BrMenu from '@/components/BrMenu.vue';
import BrNewsList from '@/components/BrNewsList.vue';
import { buildConfiguration } from '@/utils/buildConfiguration';
import type { Configuration } from '@bloomreach/spa-sdk';
import type { BrMapping } from '@bloomreach/vue3-sdk';
import { BrComponent, BrPage } from '@bloomreach/vue3-sdk';
import axios from 'axios';
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';

const route = useRoute();

const mapping: BrMapping = {
  Banner: BrBanner,
  Content: BrContent,
  menu: BrMenu,
  'News List': BrNewsList,
  'Simple Content': BrContent,
};
const configuration = ref<Configuration>({
  ...buildConfiguration(route.fullPath, axios),
});

watch(
  () => route.fullPath,
  (newPath) => (configuration.value.path = newPath),
);
</script>

<style>
#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#app .has-edit-button {
  position: relative;
}
</style>

// examples/react/src/App.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BrComponent, BrPage, BrPageContext } from '@bloomreach/react-sdk';
import axios from 'axios';
import React, { StrictMode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Banner, Content, Menu, NewsList } from './components';
import { buildConfiguration } from './utils/buildConfiguration';

export default function App(): JSX.Element {
  const location = useLocation();

  const configuration = buildConfiguration(`${location.pathname}${location.search}`, axios);
  const mapping = { Banner, Content, 'News List': NewsList, 'Simple Content': Content };

  return (
    <StrictMode>
      <BrPage configuration={configuration} mapping={mapping}>
        <header>
          <nav className="navbar navbar-expand-sm navbar-dark sticky-top bg-dark" role="navigation">
            <div className="container">
              <BrPageContext.Consumer>
                {(page) => page
                  && (
                    <Link to={page.getUrl('/')} className="navbar-brand">
                      {page.getTitle() || 'brXM + React = ♥️'}
                    </Link>
                  )}
              </BrPageContext.Consumer>
              <div className="collapse navbar-collapse">
                <BrComponent path="menu">
                  <Menu />
                </BrComponent>
              </div>
            </div>
          </nav>
        </header>
        <section className="container flex-fill pt-3">
          <BrComponent path="main" />
        </section>
        <footer className="bg-dark text-light py-3">
          <div className="container clearfix">
            <div className="float-left pr-3">&copy; Bloomreach</div>
            <div className="overflow-hidden">
              <BrComponent path="footer" />
            </div>
          </div>
        </footer>
      </BrPage>
    </StrictMode>
  );
}
