// packages/ng-sdk/src/lib/br-page/br-page.component.ts
/*
 * Copyright 2020-2022 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { isPlatformBrowser, isPlatformServer } from '@angular/common';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import {
  AfterContentChecked,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChild,
  EventEmitter,
  Inject,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  Optional,
  Output,
  PLATFORM_ID,
  SimpleChanges,
  TemplateRef,
  Type,
  ViewChild,
} from '@angular/core';
import { makeStateKey, StateKey, TransferState } from '@angular/platform-browser';
import { Configuration, destroy, initialize, isPage, Page, PageModel } from '@bloomreach/spa-sdk';
import { BehaviorSubject, from, Subject } from 'rxjs';
import { filter, map, mapTo, pairwise, pluck, switchMap, take } from 'rxjs/operators';
import { BrComponentContext } from '../br-component.directive';
import { BrProps } from '../br-props.model';

interface BrNodeContext extends BrComponentContext {
  template?: TemplateRef<BrComponentContext>;
}

/**
 * The brXM page.
 */
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'br-page',
  templateUrl: './br-page.component.html',
})
export class BrPageComponent implements AfterContentChecked, OnChanges, OnDestroy {
  /**
   * The configuration of the SPA SDK.
   * @see https://www.npmjs.com/package/@bloomreach/spa-sdk#configuration
   */
  @Input() configuration!: Omit<Configuration, 'httpClient'>;

  /**
   * The brXM and Angular components mapping.
   */
  @Input() mapping: Record<keyof any, Type<BrProps>> = {};

  /**
   * The pre-initialized page instance or prefetched page model.
   * Mostly this property should be used to transfer state from the server-side to the client-side.
   */
  @Input() page?: Page | PageModel;

  /**
   * The TransferState key is used to transfer the state from the server-side to the client-side.
   * By default, it equals to `brPage`.
   * If `false` is passed then the state transferring feature will be disabled.
   */
  @Input() stateKey: StateKey<PageModel | undefined> | false = makeStateKey('brPage');

  /**
   * The current state of the page component.
   */
  @Output() state = new BehaviorSubject<Page | undefined>(undefined);

  /**
   * Http error handling
   */
  @Output() httpError = new EventEmitter<HttpErrorResponse>();

  @ViewChild('brNode', { static: true }) node!: TemplateRef<BrNodeContext>;

  @ContentChild(TemplateRef, { static: true }) private template?: TemplateRef<BrComponentContext>;

  private afterContentChecked$ = new Subject();

  constructor(
    private changeDetectorRef: ChangeDetectorRef,
    private httpClient: HttpClient,
    zone: NgZone,
    @Inject(PLATFORM_ID) private platform: any,
    @Optional() private transferState?: TransferState,
  ) {
    this.request = this.request.bind(this);

    this.state.pipe(pairwise(), pluck(0), filter(isPage)).subscribe(destroy);

    this.state
      .pipe(
        filter(isPage),
        switchMap((page) => this.afterContentChecked$.pipe(take(1), mapTo(page))),
      )
      .subscribe((page) => zone.runOutsideAngular(() => page.sync()));

    this.state
      .pipe(
        filter(() => isPlatformServer(this.platform)),
        filter(isPage),
      )
      .subscribe((page) => this.stateKey && this.transferState?.set(this.stateKey, page.toJSON()));
  }

  get context(): BrNodeContext {
    const page = this.state.getValue();
    const component = page?.getComponent();
    const pageOrNBR = page || this.configuration?.NBRMode;

    // if (!page || !component) {
    //   return undefined;
    // }

    return {
      component,
      page,
      $implicit: component,
      template: pageOrNBR ? this.template : undefined,
    };
  }

  async ngOnChanges(changes: SimpleChanges): Promise<void> {
    if (changes.configuration || changes.page) {
      await this.initialize(changes.page?.currentValue);
    }

    if (changes.stateKey?.previousValue && isPlatformServer(this.platform)) {
      if (changes.stateKey.currentValue && this.transferState?.hasKey(changes.stateKey.previousValue)) {
        this.transferState?.set(
          changes.stateKey.currentValue,
          this.transferState?.get(changes.stateKey.previousValue, undefined),
        );
      }

      this.transferState?.remove(changes.stateKey.previousValue);
    }
  }

  ngAfterContentChecked(): void {
    this.afterContentChecked$.next();
  }

  ngOnDestroy(): void {
    this.state.next(undefined);
    this.state.complete();
    this.afterContentChecked$.complete();
  }

  private async initialize(page: Page | PageModel | undefined): Promise<void> {
    if (this.stateKey && isPlatformBrowser(this.platform) && this.transferState?.hasKey(this.stateKey)) {
      page = page ?? this.transferState?.get(this.stateKey, undefined);
      this.transferState?.remove(this.stateKey);
    }

    const configuration = { httpClient: this.request, ...this.configuration } as Configuration;
    const observable = page ? from(initialize(configuration, page)) : from(initialize(configuration));

    observable.subscribe((state) => {
      this.state.next(state);
      this.changeDetectorRef.detectChanges();
    });
  }

  private request(...[{ data: body, headers, method, url }]: Parameters<Configuration['httpClient']>): Promise<void | {
    data: PageModel;
  }> {
    return this.httpClient
      .request<PageModel>(method, url, {
        body,
        headers: headers as Record<string, string | string[]>,
        responseType: 'json',
      })
      .pipe(map((data) => ({ data })))
      .toPromise()
      .catch((error) => this.httpError.emit(error));
  }
}

<!--
  Copyright 2020 Hippo B.V. (http://www.onehippo.com)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<ng-template #brNode let-component let-template="template">
  <ng-container [brNode]="component" [brNodeTemplate]="template">
    <ng-container [ngSwitch]="component | brNodeType">
      <ng-container
        *ngSwitchCase="'container-item'"
        [brNodeContainerItem]="component"
      ></ng-container>
      <ng-container
        *ngSwitchCase="'container'"
        [brNodeContainer]="component"
      ></ng-container>
      <ng-container
        *ngSwitchDefault
        [brNodeComponent]="component"
      ></ng-container>
    </ng-container>
  </ng-container>
</ng-template>

<ng-template
  *ngIf="context"
  [ngTemplateOutlet]="brNode"
  [ngTemplateOutletContext]="context"
></ng-template>

// packages/vue-sdk/src/BrPage.vue
<!--
  - Copyright 2020-2022 Bloomreach
  -
  - Licensed under the Apache License, Version 2.0 (the "License");
  - you may not use this file except in compliance with the License.
  - You may obtain a copy of the License at
  -
  -   http://www.apache.org/licenses/LICENSE-2.0
  -
  - Unless required by applicable law or agreed to in writing, software
  - distributed under the License is distributed on an "AS IS" BASIS,
  - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  - See the License for the specific language governing permissions and
  - limitations under the License.
  -->

<template>
  <br-node-component v-if="state || configuration.NBRMode" :component="root">
    <slot :component="root" :page="state" />
  </br-node-component>
</template>

<script lang="ts">
import { Configuration, PageModel, Page, initialize, destroy } from '@bloomreach/spa-sdk';
import { Component, Prop, Provide, Vue, Watch } from 'vue-property-decorator';
import BrNodeComponent from './BrNodeComponent.vue';

/**
 * The brXM page.
 */
@Component({
  components: { BrNodeComponent },
  computed: {
    root(this: BrPage) {
      return this.state?.getComponent();
    },
  },
  data: () => ({ state: undefined }),
  name: 'br-page',
})
export default class BrPage extends Vue {
  /**
   * The configuration of the SPA SDK.
   * @see https://www.npmjs.com/package/@bloomreach/spa-sdk#configuration
   */
  @Prop() configuration!: Configuration;

  /**
   * The brXM and Vue.js components mapping.
   */
  @Prop() mapping!: Record<keyof any, Vue.Component>; // eslint-disable-line @typescript-eslint/no-explicit-any

  /**
   * The pre-initialized page instance or prefetched page model.
   * Mostly this property should be used to transfer state from the server-side to the client-side.
   */
  @Prop() page?: Page | PageModel;

  private state?: Page;

  private loading?: Promise<Page>;

  @Provide() private mapping$() {
    return this.mapping;
  }

  @Provide() private page$() {
    return this.state;
  }

  async serverPrefetch(): Promise<void> {
    await this.loading;
  }

  destroyed(): void {
    this.destroy();
  }

  mounted(): void {
    this.state?.sync();
  }

  updated(): void {
    this.state?.sync();
  }

  @Watch('configuration', { immediate: true, deep: true })
  private async update(current: Configuration, previous?: Configuration) {
    if (!previous && this.page) {
      this.state = await initialize(this.configuration, this.page);

      return;
    }

    this.destroy();
    this.loading = initialize(this.configuration);
    this.state = await this.loading;
    delete this.loading;
  }

  private destroy() {
    if (this.state) {
      destroy(this.state);
    }
  }
}
</script>
