// examples/react/src/components/Banner.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BrManageContentButton, BrProps } from '@bloomreach/react-sdk';
import { Document, ImageSet } from '@bloomreach/spa-sdk';
import React, { JSX } from 'react';
import { Link } from 'react-router-dom';
import { sanitize } from '../utils/sanitize';

export function Banner({ component, page }: BrProps): JSX.Element | null {
  const documentRef = component?.getModels().document;
  const document = !!documentRef && page?.getContent(documentRef);

  if (!document || !page) {
    return null;
  }

  const { content, image: imageRef, link: linkRef, title } = document.getData<DocumentData>();
  const image = imageRef && page.getContent<ImageSet>(imageRef);
  const link = linkRef && page.getContent<Document>(linkRef);

  return (
    <div className={`jumbotron mb-3 ${page.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageContentButton
        content={document}
        documentTemplateQuery="new-banner-document"
        folderTemplateQuery="new-banner-folder"
        parameter="document"
        root="banners"
        relative
        pickerSelectableNodeTypes="best:banner,hap:bannerdocument"
      />
      {title && <h1>{title}</h1>}
      {image && <img className="img-fluid" src={image.getOriginal()?.getUrl()} alt={title} />}
      {/* eslint-disable-next-line react/no-danger */}
      {content && page && <div dangerouslySetInnerHTML={{ __html: page.rewriteLinks(sanitize(content.value)) }} />}
      {link && (
        <p className="lead">
          <Link to={link.getUrl()} className="btn btn-primary btn-lg" role="button">
            Learn more
          </Link>
        </p>
      )}
    </div>
  );
}

// examples/angular/src/app/components/banner/banner.component.ts
/*
 * Copyright 2024 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, Input, OnInit } from '@angular/core';
import { Component as BrComponent, Document, ImageSet, Page } from '@bloomreach/spa-sdk';
import { CommonModule } from '@angular/common';
import { BrSdkModule } from '@bloomreach/ng-sdk';
import { RouterModule } from '@angular/router';
import { sanitize } from '../../utils/sanitize';
import { ParseUrlPipe } from '../../pipes/parse-url.pipe';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'br-banner',
  standalone: true,
  imports: [
    CommonModule,
    BrSdkModule,
    RouterModule,
    ParseUrlPipe,
  ],
  templateUrl: './banner.component.html',
})
export class BannerComponent implements OnInit {
  @Input() component!: BrComponent;

  @Input() page!: Page;

  safeHTML?: string | null;

  async ngOnInit(): Promise<void> {
    const content = this.document?.getData<DocumentData>().content;
    const sanitized = sanitize(content!.value);
    this.safeHTML = this.page.rewriteLinks(sanitized);
  }

  get document(): Document | undefined {
    const { document } = this.component.getModels<DocumentModels>();

    return document && this.page.getContent<Document>(document);
  }

  get data(): DocumentData | undefined {
    return this.document?.getData<DocumentData>();
  }

  get image(): ImageSet | undefined {
    return this.data?.image && this.page.getContent<ImageSet>(this.data.image);
  }

  get link(): Document | undefined {
    // eslint-disable-next-line dot-notation
    return this.data && this.data['link'] && this.page.getContent<Document>(this.data['link']);
  }
}

<!--
  Copyright 2024 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

@if (document) {
<div class="jumbotron mb-3" [ngClass]="{ 'has-edit-button': page.isPreview() }">
  <ng-container [brManageContentButton]="document" documentTemplateQuery="new-banner-document"
    folderTemplateQuery="new-banner-folder" parameter="document" root="banners" [relative]="true"
    pickerSelectableNodeTypes="best:banner,hap:bannerdocument">
  </ng-container>
  @if (data?.title) {
  <h1>{{ data!.title }}</h1>
  }
  @if (image) {
  <img class="img-fluid" [src]="image.getOriginal()?.getUrl()" [alt]="data?.title || ''" />
  }
  @if (data?.content) {
  <div [innerHTML]="safeHTML"></div>
  }
  @if (link) {
  <p class="lead">
    <a class="btn btn-primary btn-lg" role="button" [routerLink]="(link.getUrl()! | parseUrl).pathname"
      [queryParams]="(link.getUrl()! | parseUrl).queryParams">
      Learn more
    </a>
  </p>
  }
</div>
}
