// examples/next/components/Banner.tsx
/*
 * Copyright 2019-2026 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {BrManageContentButton, BrProps} from '@bloomreach/react-sdk';
import {Document, ImageSet} from '@bloomreach/spa-sdk';
import Link from 'next/link';
import React, {JSX} from 'react';
import {sanitize} from '../utils/sanitize';

export function Banner({ component, page, isClientComponent }: BrProps): JSX.Element | null {
  const documentRef = component?.getModels<DocumentModels>().document;
  const imageVariant = component?.getParameters<BannerParameters>().imageVariant;
  const document = !!documentRef && page?.getContent(documentRef);

  if (!document) {
    return null;
  }

  const {content, image: imageRef, link: linkRef, title} = document.getData<DocumentData>();
  const imageSet = imageRef && page.getContent<ImageSet>(imageRef);
  const image = imageSet && (imageVariant ? imageSet.getVariant(imageVariant) : imageSet.getOriginal());
  const link = linkRef && page.getContent<Document>(linkRef);

  return (
    <div className={`jumbotron mb-3 ${page.isPreview() ? 'has-edit-button' : ''}`}>
      {/* buttons should only be rendered on the client side */}
      {isClientComponent && 
        <BrManageContentButton
          content={document}
          documentTemplateQuery="new-banner-document"
          folderTemplateQuery="new-banner-folder"
          parameter="document"
          root="banners"
          relative
          pickerSelectableNodeTypes="best:banner,hap:bannerdocument"
          page={page}
        />
      }
      {title && <h1>{title}</h1>}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      {image && <img className="img-fluid" src={image.getUrl()} alt={title}/>}
      {content && page && (
        <div dangerouslySetInnerHTML={{__html: page.rewriteLinks(sanitize(content.value))}}/>
      )}
      {link && (
        <p className="lead">
          <Link href={link.getUrl() ?? '/'} className="btn btn-primary btn-lg" role="button">
            Learn more
          </Link>
        </p>
      )}
    </div>
  );
}

// examples/lit/src/components/lit-banner.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { type ContainerItem, type Page, type Document, type ImageSet } from '@bloomreach/spa-sdk';
import '@bloomreach/lit-sdk';
import { sanitize } from '../utils/sanitize.js';

@customElement('lit-banner')
export class LitBanner extends LitElement {
  @property({ type: Object }) component?: ContainerItem;
  @property({ type: Object }) page?: Page;

  // Light DOM for Bootstrap CSS and EM meta comments
  createRenderRoot() {
    return this;
  }

  render() {
    if (!this.component || !this.page) return nothing;

    const documentRef = this.component.getModels<DocumentModels>().document;
    const document = documentRef && this.page.getContent(documentRef);

    if (!document) return nothing;

    const { content, image: imageRef, link: linkRef, title } = (document as any).getData<DocumentData>();
    const imageVariant = this.component.getParameters<BannerParameters>().imageVariant;
    const imageSet = imageRef && this.page.getContent<ImageSet>(imageRef);
    const image = imageSet && (imageVariant ? imageSet.getVariant(imageVariant) : imageSet.getOriginal());
    const link = linkRef && this.page.getContent<Document>(linkRef);

    return html`
      <div class="jumbotron mb-3 ${this.page.isPreview() ? 'has-edit-button' : ''}">
        <br-manage-content-button
          .content=${document}
          documentTemplateQuery="new-banner-document"
          folderTemplateQuery="new-banner-folder"
          parameter="document"
          root="banners"
          ?relative=${true}
          pickerSelectableNodeTypes="best:banner,hap:bannerdocument"
          .page=${this.page}
        ></br-manage-content-button>
        ${title ? html`<h1>${title}</h1>` : nothing}
        ${image ? html`<img class="img-fluid" src=${image.getUrl()} alt=${title || ''} />` : nothing}
        ${content && this.page
          ? html`<div>${unsafeHTML(this.page.rewriteLinks(sanitize(content.value)))}</div>`
          : nothing}
        ${link
          ? html`
            <p class="lead">
              <a href=${(link as any).getUrl()} class="btn btn-primary btn-lg" role="button">Learn more</a>
            </p>`
          : nothing}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-banner': LitBanner;
  }
}
