// examples/react/src/components/Menu.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { JSX } from 'react';
import { Link } from 'react-router-dom';
import { MenuItem, Menu as BrMenu, TYPE_LINK_EXTERNAL, isMenu } from '@bloomreach/spa-sdk';
import { BrManageMenuButton, BrProps } from '@bloomreach/react-sdk';

interface MenuLinkProps {
  item: MenuItem;
}

function MenuLink({ item }: MenuLinkProps): JSX.Element {
  const url = item.getUrl();

  if (!url) {
    return <span className="nav-link text-capitalize disabled">{item.getName()}</span>;
  }

  if (item.getLink()?.type === TYPE_LINK_EXTERNAL) {
    return (
      <a className="nav-link text-capitalize" href={url}>
        {item.getName()}
      </a>
    );
  }

  return (
    <Link to={url} className="nav-link text-capitalize">
      {item.getName()}
    </Link>
  );
}

export function Menu({ component, page }: BrProps): JSX.Element | null {
  // Try getting menu from component first (if available)
  let menuRef = component?.getModels<MenuModels>()?.menu;

  // If no component or no menu ref, try getting menu directly from page
  if (!menuRef && page) {
    const menuComponent = page.getComponent('menu');
    menuRef = menuComponent?.getModels<MenuModels>()?.menu;
  }

  const menu = menuRef && page?.getContent<BrMenu>(menuRef);

  if (!isMenu(menu)) {
    return null;
  }

  return (
    <ul className={`navbar-nav col-12 ${page?.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageMenuButton menu={menu} page={page} />
      {menu.getItems().map((item, index) => (
        // eslint-disable-next-line react/no-array-index-key
        <li key={index} className={`nav-item ${item.isSelected() ? 'active' : ''}`}>
          <MenuLink item={item} />
        </li>
      ))}
    </ul>
  );
}

// examples/lit/src/components/lit-menu.ts
import { LitElement, html, nothing } from 'lit';
import { customElement } from 'lit/decorators.js';
import { consume } from '@lit/context';
import { type Page, type Menu, type MenuItem, TYPE_LINK_EXTERNAL, isMenu } from '@bloomreach/spa-sdk';
import { brPageContext } from '@bloomreach/lit-sdk';
import '@bloomreach/lit-sdk';

@customElement('lit-menu')
export class LitMenu extends LitElement {
  @consume({ context: brPageContext, subscribe: true })
  private _page?: Page;

  // Light DOM for Bootstrap CSS and EM meta comments
  createRenderRoot() {
    return this;
  }

  private _getMenu(): Menu | undefined {
    if (!this._page) return undefined;

    // Try getting menu from the "menu" named component
    const menuComponent = this._page.getComponent()?.getComponent('menu');
    if (!menuComponent) return undefined;

    const menuRef = menuComponent.getModels<MenuModels>()?.menu;
    if (!menuRef) return undefined;

    const menu = this._page.getContent<Menu>(menuRef);
    return isMenu(menu) ? menu : undefined;
  }

  private _renderItem(item: MenuItem) {
    const url = item.getUrl();

    if (!url) {
      return html`<span class="nav-link text-capitalize disabled">${item.getName()}</span>`;
    }

    if (item.getLink()?.type === TYPE_LINK_EXTERNAL) {
      return html`<a class="nav-link text-capitalize" href=${url}>${item.getName()}</a>`;
    }

    return html`<a href=${url} class="nav-link text-capitalize">${item.getName()}</a>`;
  }

  render() {
    const menu = this._getMenu();
    if (!menu) return nothing;

    return html`
      <ul class="navbar-nav col-12 ${this._page?.isPreview() ? 'has-edit-button' : ''}">
        <br-manage-menu-button .menu=${menu}></br-manage-menu-button>
        ${menu.getItems().map((item) => html`
          <li class="nav-item ${item.isSelected() ? 'active' : ''}">
            ${this._renderItem(item)}
          </li>
        `)}
      </ul>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-menu': LitMenu;
  }
}
