// examples/next/components/Content.tsx
/*
 * Copyright 2019-2023 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {BrManageContentButton, BrProps} from '@bloomreach/react-sdk';
import {Document, ImageSet} from '@bloomreach/spa-sdk';
import React from 'react';
import {sanitize} from "../utils/sanitize";

export function Content(props: BrProps): JSX.Element | null {
  const documentRef = props.component?.getModels<DocumentModels>().document;
  const document = documentRef && props.page?.getContent<Document>(documentRef);

  if (!document) {
    return null;
  }

  const {
    author,
    content,
    publicationDate,
    date = publicationDate,
    image: imageRef,
    title,
  } = document.getData<DocumentData>();
  const image = imageRef && props.page?.getContent<ImageSet>(imageRef);

  return (
    <div className={props.page?.isPreview() ? 'has-edit-button' : ''}>
      <BrManageContentButton content={document}/>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      {image && <img className="img-fluid mb-3" src={image.getOriginal()?.getUrl()} alt={title}/>}
      {title && <h1>{title}</h1>}
      {author && <p className="mb-3 text-muted">{author}</p>}
      {date && <p className="mb-3 small text-muted">{new Date(date).toDateString()}</p>}
      {content && (
        <div dangerouslySetInnerHTML={{__html: props.page!.rewriteLinks(sanitize(content.value))}}/>
      )}
    </div>
  );
}

// examples/lit/src/components/lit-content.ts
import { LitElement, html, nothing } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import { type ContainerItem, type Page, type Document, type ImageSet } from '@bloomreach/spa-sdk';
import '@bloomreach/lit-sdk';
import { sanitize } from '../utils/sanitize.js';

@customElement('lit-content')
export class LitContent extends LitElement {
  @property({ type: Object }) component?: ContainerItem;
  @property({ type: Object }) page?: Page;

  // Light DOM for Bootstrap CSS and EM meta comments
  createRenderRoot() {
    return this;
  }

  render() {
    if (!this.component || !this.page) return nothing;

    const documentRef = this.component.getModels<DocumentModels>().document;
    const document = documentRef && this.page.getContent<Document>(documentRef);

    if (!document) return nothing;

    const {
      author,
      content,
      publicationDate,
      date = publicationDate,
      image: imageRef,
      title,
    } = document.getData<DocumentData>();
    const image = imageRef && this.page.getContent<ImageSet>(imageRef);

    return html`
      <div class="${this.page.isPreview() ? 'has-edit-button' : ''}">
        <br-manage-content-button .content=${document} .page=${this.page}></br-manage-content-button>
        ${image ? html`<img class="img-fluid mb-3" src=${image.getOriginal()?.getUrl() || ''} alt=${title || ''} />` : nothing}
        ${title ? html`<h1>${title}</h1>` : nothing}
        ${author ? html`<p class="mb-3 text-muted">${author}</p>` : nothing}
        ${date ? html`<p class="mb-3 small text-muted">${new Date(date).toDateString()}</p>` : nothing}
        ${content ? html`<div>${unsafeHTML(this.page.rewriteLinks(sanitize(content.value)))}</div>` : nothing}
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-content': LitContent;
  }
}
