// packages/vue3-sdk/src/BrContainerUnorderedList.vue
<!--
  Copyright 2023 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->
<template>
  <render />
</template>

<script setup lang="ts">
import type { Page } from '@bloomreach/spa-sdk';
import { computed, h, useSlots } from 'vue';

const props = defineProps<{ page?: Page }>();
const slots = useSlots();
const isPreview = computed(() => props.page?.isPreview());

const render = () => h(
  'ul',
  { class: { 'hst-container': isPreview } },
  slots.default?.().map((node) => h(
    'li',
    { class: { 'hst-container-item': isPreview } },
    [node],
  )),
);
</script>

// packages/ng-sdk/src/lib/br-container-unordered-list/br-container-unordered-list.component.ts
/*
 * Copyright 2020-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, HostBinding, Input } from '@angular/core';
import { Container, Page } from '@bloomreach/spa-sdk';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'ul.br-container-unordered-list',
  templateUrl: './br-container-unordered-list.component.html',
})
export class BrContainerUnorderedListComponent {
  @Input() component!: Container;

  @Input() page!: Page;

  @HostBinding('class.hst-container')
  get isPreview(): boolean {
    return this.page?.isPreview();
  }
}

<!--
  Copyright 2020-2026 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

@for (child of component.getChildren(); track $index) {
<li [ngClass]="{ 'hst-container-item': page.isPreview() }">
  <ng-container [brComponent]="child"></ng-container>
</li>
}
