// examples/angular/src/app/menu/menu.component.ts
/*
 * Copyright 2020-2023 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, HostBinding, Input } from '@angular/core';
import { Component as BrComponent, Menu, Page, isMenu } from '@bloomreach/spa-sdk';

@Component({
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: 'ul.br-menu',
  templateUrl: './menu.component.html',
})
export class MenuComponent {
  @Input() component!: BrComponent;

  @Input() page!: Page;

  @HostBinding('class') class = 'navbar-nav col-12';

  @HostBinding('class.has-edit-button')
  get isPreview(): boolean {
    return this.page.isPreview();
  }

  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
  get menu() {
    const menuRef = this.component.getModels<MenuModels>()?.menu;
    const menu = menuRef && this.page.getContent<Menu>(menuRef);

    return isMenu(menu) ? menu : undefined;
  }
}

<!--
  Copyright 2020-2023 Bloomreach

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

   https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  -->

<ng-template [ngIf]="menu">
  <ng-container [brManageMenuButton]="menu"></ng-container>

  <li
    *ngFor="let item of menu.getItems()"
    key="{index}"
    class="nav-item"
    [ngClass]="{ active: item.isSelected() }"
  >
    <span *ngIf="!item.getUrl()" class="nav-link text-capitalize disabled">
      {{ item.getName() }}
    </span>

    <a
      *ngIf="item.getLink() | isExternalLink"
      class="nav-link text-capitalize"
      [href]="item.getUrl()"
    >
      {{ item.getName() }}
    </a>

    <a
      *ngIf="item.getLink() | isInternalLink"
      class="nav-link text-capitalize"
      [routerLink]="(item.getUrl()! | parseUrl).pathname"
      [queryParams]="(item.getUrl()! | parseUrl).queryParams"
    >
      {{ item.getName() }}
    </a>
  </li>
</ng-template>

// examples/react/src/components/Menu.tsx
/*
 * Copyright 2019-2025 Bloomreach
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { JSX } from 'react';
import { Link } from 'react-router-dom';
import { MenuItem, Menu as BrMenu, TYPE_LINK_EXTERNAL, isMenu } from '@bloomreach/spa-sdk';
import { BrManageMenuButton, BrProps } from '@bloomreach/react-sdk';

interface MenuLinkProps {
  item: MenuItem;
}

function MenuLink({ item }: MenuLinkProps): JSX.Element {
  const url = item.getUrl();

  if (!url) {
    return <span className="nav-link text-capitalize disabled">{item.getName()}</span>;
  }

  if (item.getLink()?.type === TYPE_LINK_EXTERNAL) {
    return (
      <a className="nav-link text-capitalize" href={url}>
        {item.getName()}
      </a>
    );
  }

  return (
    <Link to={url} className="nav-link text-capitalize">
      {item.getName()}
    </Link>
  );
}

export function Menu({ component, page, mapping }: BrProps): JSX.Element | null {
  const menuRef = component?.getModels<MenuModels>()?.menu;
  const menu = menuRef && page?.getContent<BrMenu>(menuRef);

  if (!isMenu(menu)) {
    return null;
  }

  return (
    <ul className={`navbar-nav col-12 ${page?.isPreview() ? 'has-edit-button' : ''}`}>
      <BrManageMenuButton menu={menu} page={page} mapping={mapping} />
      {menu.getItems().map((item, index) => (
        // eslint-disable-next-line react/no-array-index-key
        <li key={index} className={`nav-item ${item.isSelected() ? 'active' : ''}`}>
          <MenuLink item={item} />
        </li>
      ))}
    </ul>
  );
}
